version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        RUBY_VERSION: 3.3.0
    volumes:
      - ./backend:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3001:3001"
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /usr/local/bundle
      REDIS_URL: redis://redis:6379/0
    command: ./bin/rails server -b 0.0.0.0
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  bundle_data:
